version: '3'
services:
  dbmysql2:
    image: mysql:5.7
    container_name: dbmysql2
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    container_name: pma2
    links:
      - dbmysql2
    environment:
      PMA_HOST: dbmysql2
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
volumes:
  dbdata:
